### ISSUE TITLE
composer update failes

### ISSUE THREAD

**Issue by rabol** [alt-design/Alt-Starter-Kit#2]
Hi

on a fresh installation i do this:
```
composer update
```

and get this:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires alt-design/alt-starter-kit ^1.0, found alt-design/alt-starter-kit[v1.0] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.
```

**Comment by Alt-Ben** [comment]
Hey @rabol!

Should be resolved now, you'll need to re-run the install command if you use it again.

If you're still using the above, just remove the alt-design/alt-starter-kit from the composer.json and re-run the ```composer update``` command, that should be enough to resolve this.
